[package]
name = "china_identification_card"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A Rust library for validating Chinese identification card numbers based on official rules and checksums."
keywords = ["china", "id", "identification", "card", "validation"]
repository = "https://github.com/ltpp-universe/china_identification_card"

[dependencies]
