[package]
name = "china_identification_card"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "A Rust library for validating Chinese identification card numbers based on official rules and checksums."
keywords = ["china", "id", "identification", "card", "validation"]
repository = "https://github.com/ltpp-universe/china_identification_card"
categories = ["authentication", "data-structures", "development-tools"]

[dependencies]
